/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.software;
//hola mundo
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
//hola
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
