/*
=====================================================
UNIVERSIDAD: Univerdidad Tècnica de Cotopaxi
CARRERA: SOFTWARE
MATERIA: PROGRAMACION ESTRUCTURADA
ESTUDIANTE: ANDERSON SANTAFE
TEMA: CALCULADORA BASICA
DOCENTE: Ingeniero Diego Reinoso
FECHA: 04/06/2026
DESCRIPCION:
Programa que realiza operaciones basicas
como suma, resta, multiplicacion y division.
PROGRAMA PARA SUBIR NOTA
REALIZAR 25 COMMITS
/*
=====================================================
 * This source file was generated by the Gradle 'init' task
 */
package com.example.software;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "CALCULADORA!";
    }
    
    public static void main(String[] args) {
      // CREAR EL SCANNER
      //SE CREA ESCANER PARA QUE FUNCIONE
        Scanner entrada = new Scanner(System.in);

        // VARIABLES PARA LAS OPERACIONES
        //valor numero 1
        double num1;
        //valor numero 2
        double num2;
        //resultado impreso
        double resultado;
        //OPCION PREFERENTE DEL USUARIO
        int opcion;

        // TITULO DE LA CALCULADORA BASICA
        System.out.println("=========================================");
        System.out.println("     CALCULADORA DE OPERACIONES BASICAS      ");
        System.out.println("=========================================");

        // PEDIR NUMEROS (cualquier numero)
        System.out.print("Ingrese el primer numero: ");
        num1 = entrada.nextDouble();
        //sistema pide el segundo valor
        System.out.print("Ingrese el segundo numero: ");
        num2 = entrada.nextDouble();
        
        System.out.println("========================");
        System.out.println("MENU DE OPCIONES ");
        System.out.println("========================");

        // MENU DE OPCIONES EN BASE A LAS OPERACIONES
        System.out.println("\nSeleccione una opcion:");
        //SUMA
        System.out.println("-------------------------------------");
        System.out.println("1. Suma");
        System.out.println("-------------------------------------");
        //RESTA
        System.out.println("-------------------------------------");
        System.out.println("2. Resta");
        System.out.println("-------------------------------------");
        //MULTIPLICACION
        System.out.println("-------------------------------------");
        System.out.println("3. Multiplicacion");
        System.out.println("-------------------------------------");
        //DIVISION
        System.out.println("-------------------------------------");
        System.out.println("4. Division");
        System.out.println("-------------------------------------");
        
        //EL SISTEMA TE DA A ELEGIR LA OPCION DESEADA

        System.out.print("Opcion: ");
        opcion = entrada.nextInt();

        // OPERACIONES DEL  PROGRAMA REALIZADO
        switch (opcion) {

            case 1:
                resultado = num1 + num2;
                
                System.out.println("La suma es: " + resultado);
                break;
                //el valor resultante en esta casilla es la suma de dos valores dados 

            case 2:
                resultado = num1 - num2;
                System.out.println("La resta es: " + resultado);
                break;
                //el valor resultante en esta casilla es la reta de dos valores dados

            case 3:
                resultado = num1 * num2;
                System.out.println("La multiplicacion es: " + resultado);
                break;
                //el valor resultante en esta casilla es la multiplicacion de dos valores dados
                
            case 4:

                // VALIDAR DIVISION PARA EVITAR ERROR
                if (num2 != 0) {

                    resultado = num1 / num2;
                    System.out.println("La division es: " + resultado);

                } else {

                    System.out.println("No se puede dividir para cero");

                }

                break;

            default:
                System.out.println("Opcion incorrecta");
        }
//=====================================================
// FINALIZACION DEL PROGRAMA
// SE CIERRA EL SCANNER PARA AHORRAR MEMORIA
//=====================================================

        // CERRAR SCANNER
        entrada.close();
    }
}