/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.software;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
//hola
    
    public static void main(String[] args) {
      // CREAR EL SCANNER
        Scanner entrada = new Scanner(System.in);

        // VARIABLES
        double num1;
        double num2;
        double resultado;
        int opcion;

        // TITULO
        System.out.println("=========================================");
        System.out.println("     CALCULADORA DE OPERACIONES BASICAS      ");
        System.out.println("=========================================");

        // PEDIR NUMEROS (cualquier numero)
        System.out.print("Ingrese el primer numero: ");
        num1 = entrada.nextDouble();
        //sistema pide el segundo valor
        System.out.print("Ingrese el segundo numero: ");
        num2 = entrada.nextDouble();
        
        System.out.println("========================");
        System.out.println("MENU DE OPCIONES ");
        System.out.println("========================");

        // MENU DE OPCIONES EN BASE A LAS OPERACIONES
        System.out.println("\nSeleccione una opcion:");
        //SUMA
        System.out.println("1. Suma");
        //RESTA
        System.out.println("2. Resta");
        //MULTIPLICACION
        System.out.println("3. Multiplicacion");
        //DIVISION
        System.out.println("4. Division");
        //EL SISTEMA TE DA A ELEGIR LA OPCION DESEADA

        System.out.print("Opcion: ");
        opcion = entrada.nextInt();

        // OPERACIONES
        switch (opcion) {

            case 1:
                resultado = num1 + num2;
                System.out.println("La suma es: " + resultado);
                break;

            case 2:
                resultado = num1 - num2;
                System.out.println("La resta es: " + resultado);
                break;

            case 3:
                resultado = num1 * num2;
                System.out.println("La multiplicacion es: " + resultado);
                break;

            case 4:

                // VALIDAR DIVISION PARA EVITAR ERROR
                if (num2 != 0) {

                    resultado = num1 / num2;
                    System.out.println("La division es: " + resultado);

                } else {

                    System.out.println("No se puede dividir para cero");

                }

                break;

            default:
                System.out.println("Opcion incorrecta");
        }

        // CERRAR SCANNER
        entrada.close();
    }
}